name: 'ncc action'
description: 'use @vercel/ncc to compile and push your github action dist! 🚀'
author: 'Tal Hayut'
inputs:
  github_token: 
    description: 'github access token'
    required: true
  src: 
    description: 'source code dir/file to compile'
    required: true
  branch:  
    description: 'the destination branch'
    default: 'master'
    required: false
  commit_msg:  
    description: 'commit message used when pushing dist'
    default: 'action dist 📦'
    required: false
  ncc_args:
    description: 'comma seperated args for ncc'
    required: false
  allow_unrelated:
    description: 'enable allow unrelated history flag for git pull'
    default: 'true'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'green'
