name: 'ncc action'
description: 'use @zeit/ncc to compile and push your github action dist! 🚀'
author: 'Tal Hayut'
inputs:
  src: 
    description: 'source code dir/file to compile'
    required: true
  ncc_args:
    description: 'comma seperated args for ncc'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'green'
