name: bump

on:
  push:
    branches:
      - release

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/bump@next
      with:
        github_token: ${{ secrets.GP_TOKEN }}